version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: vending_machine_db
    restart: always
    environment:
      POSTGRES_USER: user_iot
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: vending_machine
    ports:
      - "5433:5432" # Host 5433 -> Container 5432
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - vending_network

  # Backend Service
  backend:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/Dockerfile.backend
    container_name: vending_machine_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user_iot:password123@db:5432/vending_machine
      PORT: 5000
      # Các biến môi trường khác từ .env backend
    ports:
      - "5000:5000"
    networks:
      - vending_network

  # Frontend Service
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/Dockerfile.frontend
    container_name: vending_machine_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" # Map host 3000 -> container 80 (nginx)
    networks:
      - vending_network

volumes:
  postgres_data_v2:


networks:
  vending_network:
    driver: bridge
