version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vending_machine_db
    restart: always
    environment:
      POSTGRES_USER: user_iot
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: vending_machine
    ports:
      - "5433:5432" # Map host 5433 -> container 5432
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:
